---
name: CICD

on:
  push:

concurrency:
  group: ${{ github.ref }}
  # main should run through entire queue of commits for debugging
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  build-and-push-builder-images:
    name: "Build and Push Builder Images"
    # auth-ing to GHCR with same same user may cause problems
    # run_id is a backup if token is undefined
    concurrency: ${{ github.token || github.run_id }}
    runs-on: ubuntu-20.04
    steps:
      - name: Test
        run: echo "Test"
